var programs = [
{"NAME":"Accounting"},
{"NAME":"Everest University-South Orlando","CITY":"Orlando","ST":"FL"},
{"NAME":"Administrative Assistant"},
{"NAME":"Administrative Medical Assistant"},
{"NAME":"Administrative Office Technology"},
{"NAME":"Applied Automotive Technology"},
{"NAME":"Applied Management"},
{"NAME":"Automotive Technology"},
{"NAME":"Automotive Technology and Management"},
{"NAME":"Biomedical Engineering Technology"},
{"NAME":"Business"},
{"NAME":"Business Accounting"},
{"NAME":"Business Administration"},
{"NAME":"Business Management"},
{"NAME":"Business Operations"},
{"NAME":"Career Access Program"},
{"NAME":"Carpentry"},
{"NAME":"Collision Technology"},
{"NAME":"Computer and Electronics Engineering Technology"},
{"NAME":"Computer Drafting and Design"},
{"NAME":"Computer Engineering Technology"},
{"NAME":"Computer Forensics"},
{"NAME":"Computer Information Systems"},
{"NAME":"Computer Office Technology"},
{"NAME":"Computer Science"},
{"NAME":"Computer Technology"},
{"NAME":"Construction Management"},
{"NAME":"Construction Technology"},
{"NAME":"Criminal Investigations"},
{"NAME":"Criminal Justice"},
{"NAME":"Criminology and Forensic Technology"},
{"NAME":"Dental Assistant"},
{"NAME":"Diagnostic Cardiac Sonogram"},
{"NAME":"Diesel Technology"},
{"NAME":"Digital Entertainment and Game Design"},
{"NAME":"Digital Marketing"},
{"NAME":"Drafting and Design Technology"},
{"NAME":"Electrical Engineering Technology"},
{"NAME":"Electrical Technician"},
{"NAME":"Electrician"},
{"NAME":"Electronics Computer Technology"},
{"NAME":"Electronics Engineering Technology"},
{"NAME":"Electronics Technology"},
{"NAME":"Entrepreneurship"},
{"NAME":"Executive Assistant"},
{"NAME":"Film and Video"},
{"NAME":"Finance"},
{"NAME":"Graphic Communications and Design"},
{"NAME":"Health Care Administration"},
{"NAME":"Health Care Management"},
{"NAME":"Health Information Technology"},
{"NAME":"Heating Ventilation and Air Conditioning"},
{"NAME":"Homeland Security"},
{"NAME":"Hospitality Management"},
{"NAME":"Human Resources"},
{"NAME":"Industrial Electrical Technology"},
{"NAME":"Industrial Engineering Technology"},
{"NAME":"Information Systems Administration"},
{"NAME":"Information Systems Security"},
{"NAME":"Information Technology (IT) "},
{"NAME":"Legal Assistant"},
{"NAME":"Legal Assistant/Paralegal"},
{"NAME":"Management"},
{"NAME":"Marketing"},
{"NAME":"Massage Therapy"},
{"NAME":"Medical Administrative Assistant"},
{"NAME":"Medical Assistant"},
{"NAME":"Medical Insurance Billing & Coding"},
{"NAME":"Medical Office Administration"},
{"NAME":"Mobile Communications Technology"},
{"NAME":"Motorcycle Technician"},
{"NAME":"Motorsports Chassis Fabrication"},
{"NAME":"Network & Communications Management"},
{"NAME":"Network and Internet Security Specialist"},
{"NAME":"Network Systems Administration"},
{"NAME":"Network Tech "},
{"NAME":"Nursing"},
{"NAME":"Office Skills"},
{"NAME":"Paralegal"},
{"NAME":"Patient Care Technician"},
{"NAME":"Pharmacy Technician"},
{"NAME":"Pharmacy Technology"},
{"NAME":"Plumbing Technology"},
{"NAME":"Practical Nursing"},
{"NAME":"Project Management"},
{"NAME":"Radiologic Technician"},
{"NAME":"Radiologic Technology"},
{"NAME":"Respiratory Care"},
{"NAME":"Sales"},
{"NAME":"Small Business Management"},
{"NAME":"Software Development"},
{"NAME":"Street Rod and Custom Fabrication"},
{"NAME":"Surgical Technologist"},
{"NAME":"Technical Management"},
{"NAME":"Veterinary Technology"},
{"NAME":"Visual Communications"},
{"NAME":"Web Design"}
]
